#!/usr/bin/env node
/**
 * Generates the service-area map geometry at BUILD TIME into a plain data file.
 *
 * Why not Google Maps:
 *   - Requires an API key and an active billing account (Maps JS is ~$7/1000 loads)
 *   - Ships ~200KB+ of third-party JavaScript, on a site that currently ships zero
 *   - Adds an external request to a page we deliberately kept self-contained
 *   - Map embeds carry no SEO value; the markers here are real <a> links, so this
 *     version actually *helps* crawl depth to the 52 city pages
 *
 * Uses the Albers USA projection, which is the standard for a 50-state view — it
 * repositions Alaska and Hawaii as insets rather than leaving Honolulu 3,000
 * miles off-canvas.
 *
 * Run: npm run map   (only needed if the city list changes)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { geoAlbersUsa, geoPath } from 'd3-geo';
import { feature, mesh } from 'topojson-client';
import { presimplify, simplify } from 'topojson-simplify';
import { CITIES } from '../src/data/cities.js';

const W = 960, H = 600;
const raw = JSON.parse(readFileSync('/tmp/us-states.json', 'utf8'));

// The source is 10m resolution — far more detail than a 960px-wide decorative
// map can show, and inlining it raw would add ~130KB to every page. Simplify
// the topology (which preserves shared borders, unlike simplifying paths
// independently) then round coordinates to whole pixels.
const topo = simplify(presimplify(raw), 0.6);
const states = feature(topo, topo.objects.states);

const projection = geoAlbersUsa().fitSize([W, H], states);
const path = geoPath(projection);

// Outer national outline + internal state borders, drawn separately so the
// borders can be styled thinner than the coastline.
/** Round every coordinate to 1dp — sub-pixel precision is invisible here. */
const round = (d) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(n * 10) / 10));

const nation = round(path(mesh(topo, topo.objects.states, (a, b) => a === b)));
const borders = round(path(mesh(topo, topo.objects.states, (a, b) => a !== b)));

const points = [];
const dropped = [];
for (const c of CITIES) {
  const p = projection([c.lng, c.lat]);
  if (!p || Number.isNaN(p[0])) { dropped.push(c.slug); continue; }
  points.push({
    slug: c.slug, name: c.name, state: c.state,
    x: Math.round(p[0] * 10) / 10,
    y: Math.round(p[1] * 10) / 10,
  });
}

/**
 * Collision resolution. Genuinely adjacent metros — Dallas/Fort Worth/Arlington
 * sit ~4px apart at this scale — would render as one unreadable blob and their
 * links would be unclickable. A few relaxation passes push overlapping markers
 * just far enough apart to be distinct and tappable. The displacement is a
 * couple of pixels on a 960px map, so the geography stays honest.
 */
const MIN = 13;
let moved = 0;
for (let pass = 0; pass < 60; pass++) {
  let shifted = false;
  for (let i = 0; i < points.length; i++)
    for (let j = i + 1; j < points.length; j++) {
      const a = points[i], b = points[j];
      let dx = b.x - a.x, dy = b.y - a.y;
      let d = Math.hypot(dx, dy);
      if (d >= MIN) continue;
      if (d === 0) { dx = 0.6; dy = 0.6; d = Math.hypot(dx, dy); }   // exact overlap
      const push = (MIN - d) / 2;
      const ux = (dx / d) * push, uy = (dy / d) * push;
      a.x -= ux; a.y -= uy; b.x += ux; b.y += uy;
      shifted = true;
    }
  if (!shifted) break;
  moved++;
}
for (const p of points) { p.x = Math.round(p.x * 10) / 10; p.y = Math.round(p.y * 10) / 10; }

const clashes = [];
for (let i = 0; i < points.length; i++)
  for (let j = i + 1; j < points.length; j++) {
    const d = Math.hypot(points[i].x - points[j].x, points[i].y - points[j].y);
    if (d < MIN - 0.5) clashes.push(`${points[i].slug}↔${points[j].slug} (${d.toFixed(1)}px)`);
  }
console.log(`  collision   ${moved} relaxation pass(es)`);

const out = `// GENERATED by scripts/gen-map.mjs — do not edit by hand.
// Regenerate with: npm run map
export const MAP = ${JSON.stringify({ width: W, height: H, nation, borders, points }, null, 1)};
`;
writeFileSync('src/data/map.js', out);

console.log(`✓ src/data/map.js written`);
console.log(`  viewBox     ${W}x${H}`);
console.log(`  outline     ${nation.length} path chars`);
console.log(`  borders     ${borders.length} path chars`);
console.log(`  plotted     ${points.length}/${CITIES.length} cities`);
if (dropped.length) console.log(`  ✗ DROPPED  ${dropped.join(', ')}`);
if (clashes.length) {
  console.log(`  ⚠ ${clashes.length} marker pair(s) closer than ${MIN}px:`);
  clashes.slice(0, 6).forEach((c) => console.log(`      ${c}`));
}
